// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oetumfqiubtotzguymxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ldHVtZnFpdWJ0b3R6Z3V5bXhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MzQ1NzEsImV4cCI6MjA2NjExMDU3MX0.aJp7FdcI41xMqPms0QstnVtf_PAlIzrOz8TvboYzx6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);